server:
  port: 8889

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8888/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
spring:
  application:
    name: currency-service