spring:
  application:
    name: account-resource
server:
  port: 1111
management:
  port: 1112
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8888/eureka
  instance:
    lease-renewal-interval-in-seconds: 5